<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NX00441" failures="0" tests="6" name="nextbridge.com_VisualValidation_MainCode.mainPage" time="53.611" errors="1" timestamp="2020-03-05T20:00:03 PKT" skipped="0">
  <testcase classname="nextbridge.com_VisualValidation_MainCode.mainPage" name="mainPageOpening" time="5.443"/>
  <testcase classname="nextbridge.com_VisualValidation_MainCode.mainPage" name="Destroy" time="0.006">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at nextbridge.com_VisualValidation_MainCode.mainPage.Destroy(mainPage.java:197)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Destroy -->
  <testcase classname="nextbridge.com_VisualValidation_MainCode.mainPage" name="roboticsMachineDesign" time="11.527"/>
  <testcase classname="nextbridge.com_VisualValidation_MainCode.mainPage" name="technologiesLanguageAndFramework" time="12.156"/>
  <testcase classname="nextbridge.com_VisualValidation_MainCode.mainPage" name="lookInsideInitiatives" time="12.933"/>
  <testcase classname="nextbridge.com_VisualValidation_MainCode.mainPage" name="lookInsideEvents" time="11.546"/>
</testsuite> <!-- nextbridge.com_VisualValidation_MainCode.mainPage -->
